# CI/CD pipeline for the outbound-calling-app
#
# Build once, then deploy to dev → qa → prod via Amazon ECS.
# Dev deploys automatically on push to main; QA and Prod require
# manual approval via GitHub Environment protection rules.
#
# GitHub Environment Setup (manual):
#   Settings → Environments → Create "qa"  → Add required reviewers
#   Settings → Environments → Create "prod" → Add required reviewers
#
# To enable deployments:
#   1. Fill in the TODO placeholders below with your AWS values
#   2. Uncomment the deploy-dev, deploy-qa, and deploy-prod jobs
#   3. Push to main

name: Deploy Outbound Calling App

on:
  push:
    branches: [main]
    paths:
      - "outbound-calling-app/**"
  workflow_dispatch:

# TODO: Replace these placeholder values with your actual AWS configuration
env:
  AWS_REGION: us-east-1 # TODO: your AWS region
  ECR_REPOSITORY: outbound-calling-app # TODO: your ECR repository name
  ECS_CLUSTER: my-cluster # TODO: your ECS cluster name
  ECS_SERVICE: outbound-calling-app # TODO: your ECS service name
  TASK_DEFINITION_FAMILY: outbound-calling-app # TODO: your task definition family
  CONTAINER_NAME: outbound-calling-app # TODO: container name in task definition
  AWS_ROLE_ARN_DEV: arn:aws:iam::123456789012:role/github-actions-dev # TODO: dev IAM role ARN
  AWS_ROLE_ARN_QA: arn:aws:iam::123456789012:role/github-actions-qa # TODO: qa IAM role ARN
  AWS_ROLE_ARN_PROD: arn:aws:iam::123456789012:role/github-actions-prod # TODO: prod IAM role ARN

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-tag.outputs.image-tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        id: set-tag
        run: echo "image-tag=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Build Docker image (validation only)
        run: docker build -t outbound-calling-app:${{ steps.set-tag.outputs.image-tag }} ./outbound-calling-app

  # ---------------------------------------------------------------
  # Uncomment the jobs below when AWS credentials are configured.
  # ---------------------------------------------------------------

  # deploy-dev:
  #   name: Deploy to Dev
  #   needs: build
  #   uses: ./workflows/reusable-deploy-ecs.yml
  #   with:
  #     environment: dev
  #     aws-role-arn: ${{ env.AWS_ROLE_ARN_DEV }}  # NOTE: see workaround below
  #     aws-region: us-east-1  # TODO: your AWS region
  #     ecr-repository: outbound-calling-app  # TODO: your ECR repository name
  #     image-tag: ${{ needs.build.outputs.image-tag }}
  #     ecs-cluster: my-cluster  # TODO: your ECS cluster name
  #     ecs-service: outbound-calling-app  # TODO: your ECS service name
  #     task-definition-family: outbound-calling-app  # TODO: your task definition family
  #     container-name: outbound-calling-app  # TODO: container name in task definition

  # deploy-qa:
  #   name: Deploy to QA
  #   needs: deploy-dev
  #   uses: ./workflows/reusable-deploy-ecs.yml
  #   with:
  #     environment: qa
  #     aws-role-arn: ${{ env.AWS_ROLE_ARN_QA }}  # NOTE: see workaround below
  #     aws-region: us-east-1  # TODO: your AWS region
  #     ecr-repository: outbound-calling-app  # TODO: your ECR repository name
  #     image-tag: ${{ needs.build.outputs.image-tag }}
  #     ecs-cluster: my-cluster  # TODO: your ECS cluster name
  #     ecs-service: outbound-calling-app  # TODO: your ECS service name
  #     task-definition-family: outbound-calling-app  # TODO: your task definition family
  #     container-name: outbound-calling-app  # TODO: container name in task definition

  # deploy-prod:
  #   name: Deploy to Prod
  #   needs: deploy-qa
  #   uses: ./workflows/reusable-deploy-ecs.yml
  #   with:
  #     environment: prod
  #     aws-role-arn: ${{ env.AWS_ROLE_ARN_PROD }}  # NOTE: see workaround below
  #     aws-region: us-east-1  # TODO: your AWS region
  #     ecr-repository: outbound-calling-app  # TODO: your ECR repository name
  #     image-tag: ${{ needs.build.outputs.image-tag }}
  #     ecs-cluster: my-cluster  # TODO: your ECS cluster name
  #     ecs-service: outbound-calling-app  # TODO: your ECS service name
  #     task-definition-family: outbound-calling-app  # TODO: your task definition family
  #     container-name: outbound-calling-app  # TODO: container name in task definition

  # NOTE: `env.*` context is not available in `with:` blocks for reusable
  # workflow calls. When uncommenting, replace the ${{ env.* }} references
  # with either:
  #   - Hard-coded values directly in the `with:` block, OR
  #   - GitHub Actions variables: ${{ vars.AWS_ROLE_ARN_DEV }}, etc.
  #     (Settings → Secrets and variables → Actions → Variables)
